const mockData = {
  name: "sk kr",
  gender: "Male",
  age: "30",
  email: "john.doe@example.com",
  phone: +1234567890,
  preferredContactMethod: "Email",
  alternatePhone: +987654321,
  emergencyContact: +1122334455,
  city: "New York",
  state: "NY",
  zip: "10001",
  country: "USA",
  qualification: "Bachelor's Degree",
  graduationYear: 2015,
  specialization: "Computer Science",
  employmentStatus: "Employed",
  jobTitle: "Software Engineer",
  currentCompany: "Tech Corp",
  experience: 8,
  linkedin: "https://www.linkedin.com/in/johndoe",
  skills: "JavaScript, React, Node.js",
  certifications: "AWS Certified Developer, PMP",
  hobbies: "Reading, Cycling, Traveling",
  languages: "English, Spanish",
  maritalStatus: "Single",
  nationality: "American",
  references: "Jane Smith - Manager (Tech Corp), Mike Johnson - Mentor",
  portfolio: "https://johndoe.dev",
  lastUpdate: "2024-12-01T10:30:00",
  timestamp: "2024-12-01T10:30:00",
};

export default mockData;