export const mockData = [
  {
    name: "sk kr",
    gender: "Male",
    age: "30",
    email: "john.doe@example.com",
    phone: "+1234567890",
    preferredContactMethod: "Email",
    alternatePhone: "+987654321",
    emergencyContact: "+1122334455",
    city: "New York",
    state: "NY",
    zip: "10001",
    country: "USA",
    qualification: "Bachelor's Degree",
    graduationYear: 2015,
    specialization: "Computer Science",
    employmentStatus: "Employed",
    jobTitle: "Software Engineer",
    currentCompany: "Tech Corp",
    experience: 8,
    linkedin: "https://www.linkedin.com/in/johndoe",
    skills: "JavaScript, React, Node.js",
    certifications: "AWS Certified Developer, PMP",
    hobbies: "Reading, Cycling, Traveling",
    languages: "English, Spanish",
    maritalStatus: "Single",
    nationality: "American",
    references: "Jane Smith - Manager (Tech Corp), Mike Johnson - Mentor",
    portfolio: "https://johndoe.dev",
    lastUpdate: "2024-12-01T10:30:00",
    timestamp: "2024-12-01T10:30:00"
  },
  {
    name: "Jane Doe",
    gender: "Female",
    age: "28",
    email: "jane.doe@example.com",
    phone: "+1234567891",
    preferredContactMethod: "Phone",
    alternatePhone: "+987654322",
    emergencyContact: "+1122334456",
    city: "San Francisco",
    state: "CA",
    zip: "94101",
    country: "USA",
    qualification: "Master's Degree",
    graduationYear: 2017,
    specialization: "Data Science",
    employmentStatus: "Employed",
    jobTitle: "Data Scientist",
    currentCompany: "Data Insights Corp",
    experience: 6,
    linkedin: "https://www.linkedin.com/in/janedoe",
    skills: "Python, R, SQL",
    certifications: "Certified Data Scientist, Six Sigma",
    hobbies: "Painting, Hiking",
    languages: "English, French",
    maritalStatus: "Married",
    nationality: "Canadian",
    references: "John Smith - Team Lead (Data Insights Corp), Emily Johnson - Professor",
    portfolio: "https://janedoe.dev",
    lastUpdate: "2024-12-01T12:00:00",
    timestamp: "2024-12-01T12:00:00"
  }
];
